-- JobHunt AI — Initial Schema
-- Run against AWS RDS PostgreSQL

-- Job listings (scraped + scored)
CREATE TABLE IF NOT EXISTS job_listings (
    id              SERIAL PRIMARY KEY,
    external_id     TEXT UNIQUE NOT NULL,          -- deduplification key
    title           TEXT NOT NULL,
    company         TEXT NOT NULL,
    location        TEXT,
    remote          BOOLEAN DEFAULT FALSE,
    url             TEXT,
    description     TEXT,
    source          TEXT,                          -- 'arbeitsagentur' | 'serpapi'
    -- CV matching output
    score           INTEGER,                       -- 0-100
    matched_skills  TEXT[],
    missing_skills  TEXT[],
    fit_reason      TEXT,
    red_flags       TEXT[],
    -- Metadata
    scraped_at      TIMESTAMPTZ DEFAULT NOW(),
    scored_at       TIMESTAMPTZ,
    date_posted     TEXT
);

CREATE INDEX IF NOT EXISTS idx_job_listings_score ON job_listings(score DESC);
CREATE INDEX IF NOT EXISTS idx_job_listings_scraped_at ON job_listings(scraped_at DESC);

-- Skill gaps (aggregated weekly)
CREATE TABLE IF NOT EXISTS skill_gaps (
    id              SERIAL PRIMARY KEY,
    skill           TEXT NOT NULL,
    frequency       INTEGER DEFAULT 1,             -- how many jobs need it
    week_start      DATE NOT NULL,
    closure_path    TEXT,                          -- fastest way to learn
    project_mapping TEXT,                          -- which of your projects demonstrates it
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(skill, week_start)
);

-- Interview prep (generated by Agent 4)
CREATE TABLE IF NOT EXISTS interview_prep (
    id              SERIAL PRIMARY KEY,
    job_id          INTEGER REFERENCES job_listings(id) ON DELETE CASCADE,
    questions       JSONB NOT NULL,                -- [{q, difficulty, star_framework, ...}]
    culture_qa      JSONB,                         -- [{q, a}]
    questions_to_ask TEXT[],
    generated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Daily report log
CREATE TABLE IF NOT EXISTS report_log (
    id              SERIAL PRIMARY KEY,
    report_date     DATE NOT NULL UNIQUE,
    jobs_found      INTEGER,
    jobs_scored     INTEGER,
    top_matches     INTEGER,
    email_sent      BOOLEAN DEFAULT FALSE,
    email_sent_at   TIMESTAMPTZ,
    summary_text    TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- Application pipeline tracking
CREATE TABLE IF NOT EXISTS applications (
    id              SERIAL PRIMARY KEY,
    job_id          INTEGER REFERENCES job_listings(id) ON DELETE CASCADE,
    status          TEXT NOT NULL DEFAULT 'saved',
                    -- 'new' | 'saved' | 'applied' | 'interview' | 'rejected' | 'offer'
    applied_at      TIMESTAMPTZ,
    last_updated    TIMESTAMPTZ DEFAULT NOW(),
    notes           TEXT,
    follow_up_sent  BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status);
